git-debimport syslog-ng_3.3.5-4.debian.tar.xz

diff --git a/debian/syslog-ng.init b/debian/syslog-ng.init
--- a/debian/syslog-ng.init
+++ b/debian/syslog-ng.init
@@ -1,14 +1,4 @@
 #! /bin/sh
-### BEGIN INIT INFO
-# Provides:          syslog-ng
-# Required-Start:    $local_fs $network $time $remote_fs
-# Required-Stop:     $local_fs $network $time $remote_fs
-# Default-Start:     2 3 4 5
-# Default-Stop:      0 1 6
-# Short-Description: Starting system logging daemon
-# Description:       Starting syslog-NG, the next generation
-#  syslog daemon.
-### END INIT INFO#
 #
 # skeleton	example file to build /etc/init.d/ scripts.
 #		This file should be used to construct scripts for /etc/init.d.
@@ -18,25 +8,15 @@
 #		by Ian Murdock <imurdock@gnu.ai.mit.edu>.
 #
 # Version:	@(#)skeleton  1.8  03-Mar-1998  miquels@cistron.nl
+#
 # This file was customized by SZALAY Attila <sasa@debian.org>
 
+PATH=/sbin:/bin:/usr/sbin:/usr/bin
 SYSLOGNG_OPTS=""
 
+test -f /sbin/syslog-ng || exit 0
 #we source /etc/default/syslog-ng if exists
 [ -r /etc/default/syslog-ng ] && . /etc/default/syslog-ng
-
-# stop syslog-ng before changing its PID file!
-PIDFILE="/var/run/syslog-ng.pid"
-
-SYSLOGNG="/usr/sbin/syslog-ng"
-NAME="syslog-ng"
-
-PATH=/sbin:/bin:/usr/sbin:/usr/bin
-test -f $SYSLOGNG || exit 0
-
-# Define LSB log_* functions.
-# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
-. /lib/lsb/init-functions
 
 case "x$CONSOLE_LOG_LEVEL" in
   x[1-8])
@@ -45,9 +25,15 @@ case "x$CONSOLE_LOG_LEVEL" in
   x)
     ;;
   *)
-    log_warning_msg "CONSOLE_LOG_LEVEL is of unaccepted value."
+    echo "CONSOLE_LOG_LEVEL is of unaccepted value."
     ;;
 esac
+
+# stop syslog-ng before changing its PID file!
+PIDFILE="/var/run/syslog-ng/syslog-ng.pid"
+
+SYSLOGNG="/sbin/syslog-ng"
+NAME="syslog-ng"
 
 create_xconsole() {
   if [ ! -e /dev/xconsole ]
@@ -64,39 +50,28 @@ create_pidfiledir() {
 }
                                 
 syslogng_start() {
-    log_daemon_msg "Starting system logging" "$NAME"
-    create_xconsole
-    [ -f "$PIDFILE" ] && echo ' seems to be running' && return 0
-    start-stop-daemon --start --quiet --exec "$SYSLOGNG" \
-                      --pidfile "$PIDFILE" -- -p "$PIDFILE"  $SYSLOGNG_OPTS
-    RET="$?"
-    log_end_msg $RET
-    return $RET
-    
+    echo -n "Starting system logging: $NAME"
+    start-stop-daemon --start --quiet --exec "$SYSLOGNG" --pidfile "$PIDFILE" -- $SYSLOGNG_OPTS \
+      || { echo " start failed."; return 1; }
+    echo "."
+    return 0
 }
 
 syslogng_stop() {
-    log_daemon_msg "Stopping system logging" "$NAME"
-    [ ! -f "$PIDFILE" ] && echo ' seems to be stopped already' && return 0
-    start-stop-daemon --stop --quiet --name "$NAME" --retry 3 \
-                      --pidfile "$PIDFILE"
-    RET="$?"
-    log_end_msg $RET
+    echo -n "Stopping system logging: $NAME"
+    start-stop-daemon --stop --quiet --name "$NAME" --retry 3 --pidfile "$PIDFILE" || { echo " not running."; return 1; }
+    echo "."
     rm -f "$PIDFILE"
-    return $RET
+    return 0
 }
 
 syslogng_reload() {
-    log_daemon_msg "Reload system logging" "$NAME"
-    if $SYSLOGNG -s $SYSLOGNG_OPTS
+    if /sbin/syslog-ng -s
     then
-      start-stop-daemon --stop --signal 1 --quiet --exec "$SYSLOGNG" \
-                        --pidfile "$PIDFILE"
-      RET="$?"
-      log_end_msg $RET
-      return $RET
+      start-stop-daemon --stop --signal 1 --quiet --exec "$SYSLOGNG" --pidfile "$PIDFILE" || return 1
+      return 0
     else
-      log_end_msg 1
+      echo "Cannot load /etc/syslog-ng/syslog-ng.conf"
       return 1
     fi
 }
@@ -104,11 +79,27 @@ syslogng_reload() {
 
 case "$1" in
   start)
+    create_xconsole
     create_pidfiledir
     syslogng_start || exit 1
     ;;
   stop)
     syslogng_stop || exit 1
+    ;;
+  reload-or-restart)
+    if [ -r "$PIDFILE" ]
+    then
+        PID=$(cat $PIDFILE)
+        EXE=$(readlink /proc/$PID/exe)
+        if [ "x$EXE" == "x/sbin/syslog-ng" ]
+        then
+            syslogng_reload || exit 1
+        else
+            syslogng_start || exit 1
+        fi
+    else
+        syslogng_start || exit 1
+    fi
     ;;
   reload|force-reload)
     syslogng_reload || exit 1
@@ -119,7 +110,7 @@ case "$1" in
     syslogng_start || exit 1
     ;;
   *)
-    echo "Usage: /etc/init.d/$NAME {start|stop|restart|reload|force-reload}" >&2
+    echo "Usage: /etc/init.d/$NAME {start|stop|restart|reload|force-reload|reload-or-restart}" >&2
     exit 1
     ;;
 esac
